### ISSUE TITLE
Fetch corresponding alphafold model doesn't work for some PDBs

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#100]
E.g., test with the tutorial model in 0.9.8.92 - nothing happens, and no alphafold model is loaded, with a warning printed to the terminal:

```
INFO:: no DBREF found in molecule header 0
```

I think either (a) if there is no database reference in the header, Coot should query the database to identify an appropriate one (in this case P05798) or (b) A text box should be generated to make it obvious why the procedure has failed.

Cheers
Oli

**Comment by pemsley** [comment]
I agree. Option (b) for now e7f2361e742557c991cecdc60267300fc45b8efc.
