### ISSUE TITLE
Default to have return accept refinement, rather than clear atom pull restraint?

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#104]
Hi Paul,

In  0.9x, after real space refinement, the return key defaults to "clear atom pull restraint" when the refinement "traffic light" window has focus (which it grabs by default post-refinement). 

Would it be possible to alter it to "accept refinement" instead, as I think this is by far the most frequent action?

Cheers
Oli

![image](https://github.com/pemsley/coot/assets/19766818/9998c4b4-9f28-493c-a2a6-aa65cfe72599)

**Comment by pemsley** [comment]
I agree.
At least in principle.
However, I have abandoned GUI work in the 0.9.x. series - too time consuming/distracting for a dead-end branch.
