### ISSUE TITLE
Help! Coot Issue - Maybe due to Mac Update?

### ISSUE THREAD

**Issue by hryan96** [pemsley/coot#105]
Hi!

I'm having some issues with coot, it keeps crashing with this error:

-ERROR- Ccoot_rebuild:56 Error in wrapper coot_rebuild 0.0:: External process exited with exit code != 0
Process: coot
-ERROR- Ccoot_rebuild:47 Error in wrapper coot_rebuild 0.0:: Error in checking external process after completion
exit status and  code: 0 1

I have deleted it and tried reinstalling with homebrew and I couldn't get it to work (i kept getting errors and fails), so I deleted all my ccp4 packages and redownloaded, which did reinstall coot but the same error is present.

I have tried changing the version of Xquartz and thats not helping. I am running Xquartz 2.8.6_beta1 and Mac Ventura 13.2.1.

I'm a bit desperate now my thesis due date is looming!

Thank you so much for any help!!

**Comment by olibclarke** [comment]
When you type `which coot` what do you see? My guess would be that your path is still pointing towards the homebrew installed coot, whereas you likely want the version of coot packaged with ccp4.

**Comment by pemsley** [comment]
I agree with @olibclarke.

**Comment by hryan96** [comment]
The error message I have on my ccp4 is the same from before I tried deleting and reinstalling

After trying to get it to install with homebrew with no look I did "brew rm coot" so I don't think that is conflicting?

"Which coot" gives me:

% which coot
coot not found

**Comment by olibclarke** [comment]
How are you launching coot? What command or graphical method? That response to `which coot` would indicate that you are not just typing `coot` at the command prompt?

**Comment by pemsley** [comment]
Related?

https://www.mail-archive.com/ccp4bb@jiscmail.ac.uk/msg54861.html

**Comment by hryan96** [comment]
Hi! I launch coot via ccp4, so I normally just select it and run?

**Comment by olibclarke** [comment]
Are you launching it from the "new" ccp4 interface or the old one? Does the interface look like this, or something else?

![image](https://github.com/pemsley/coot/assets/19766818/a6ff37ed-fdd8-4d7b-ac78-59f7b083f30b)

**Comment by hryan96** [comment]
The newer ccp4i2 interface 

<img width="1428" alt="image" src="https://github.com/pemsley/coot/assets/149125061/3bfff1a8-6eeb-4923-9d0e-59dc687e901b">
