### ISSUE TITLE
"Dynamic Distance" broken in 0.9.8.92

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#106]
Nothing happens - no distance is defined, and the cursors remains in "pick mode" after selecting two atoms.

**Comment by pemsley** [comment]
Yes, it is. Either that or unintuitive.

You are supposed to click the an atom in the "moving" fragment first.

Also, this won't be fixed (by me) due to no work on old gui.

An incoming patch to fix this would be welcome of course.
