### ISSUE TITLE
unable to install coot with homebrew on Mac M1 OS 14.0 Sonoma

### ISSUE THREAD

**Issue by Nirvana1985** [pemsley/coot#107]
I tried to follow the instructions and discussions but still unable to get it to work: 

wget https://raw.githubusercontent.com/YoshitakaMo/homebrew-bio/coot/Formula/coot.rb -O coot.rb
brew install ./coot.rb --verbose --debug --keep-tmp --HEAD 

And I got this: 
BuildError: Failed executing: ./configure --prefix=/opt/homebrew/Cellar/coot/HEAD-d6d8ed5 --with-enhanced-ligand-tools --with-boost=/opt/homebrew/opt/boost --with-boost-libdir=/opt/homebrew/opt/boost-python3/lib --with-rdkit-prefix=/opt/homebrew/opt/rdkit --with-fftw-prefix=/opt/homebrew/opt/clipper4coot/fftw2 --with-backward --with-libdw
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 5
bash-3.2$ make install
make: Nothing to be done for `install' 
I have tried both with and without --HEAD and neither has worked. 
I'm running  OS 14.0 Sonoma on Mac M1.

**Comment by pemsley** [comment]
@Nirvana1985,
Things have moved on a bit since then.
Please try this:
https://github.com/pemsley/coot/issues/33#issuecomment-1793311159

**Comment by Nirvana1985** [comment]
Hi Paul, 

I followed #33 and  tried the new coot.rb and installed python3 (python 3.12), and ran into the same problem. 
BuildError: Failed executing: ./configure --prefix=/opt/homebrew/Cellar/cootgtk4/HEAD-2810404 --with-enhanced-ligand-tools --with-boost=/opt/homebrew/opt/boost --with-boost-libdir=/opt/homebrew/opt/boost-python3/lib --with-rdkit-prefix=/opt/homebrew/opt/rdkit --with-fftw-prefix=/opt/homebrew/opt/clipper4coot/fftw2 --with-backward --with-libdw
1. raise
2. ignore
3. backtrace
4. irb
5. shell

**Comment by Nirvana1985** [comment]
Never mind,  I tried the new coot.rb by Yoshitaka Moriwaki and it worked great.
