### ISSUE TITLE
Release-0.9.8.92: FLEV not working

### ISSUE THREAD

**Issue by LanceWesterhoff** [pemsley/coot#110]
We ran into a bug (?) with FLEV in Release-0.9.8.92. We've never tried to use this tool before so perhaps either we aren't using it correctly or there is some other problem.

We performed the following steps with the attached input:

1. Open 1LRI.pdb or 1LRI_nH.pdb
2. File->Import CIF Dictionary and provide 1LRI.cif
3. Press F6 and select CLR under chain L
4. Ligand->FLEV this residue

The ligand editor appears and the following errors are reported to the screen. But no interaction diagram is presented. I'm not sure what we need to do on our end to address it, so I think it's a code problem. Or maybe we're missing a step?

Thank you for your time!

[FLEVissue.tar.gz](https://github.com/pemsley/coot/files/13441939/FLEVissue.tar.gz)

```
DEBUG:: sanitizeMol() returned with failed_op: 0 0 (note 'no-failure' is value 0).
[10:43:46] 

****
Pre-condition Violation
RingInfo not initialized
Violation occurred on line 76 in file /share/apps/Coot/BUILD/autobuild/HOSTNAME_2023-11-17__T18_09_53/rdkit-Release_2018_09_3/Code/GraphMol/RingInfo.cpp
Failed Expression: df_init
****

::::::::::::::::::::: get_fle_ligand_bonds() inputs: 
::::::::: ligand_res: 0x61daff0 [spec: 1 "L" 99 ""]
::::::::: n residues: 21
:::::::::      residue: 0 [spec: 1 "A" 87 ""]
:::::::::      residue: 1 [spec: 1 "A" 60 ""]
:::::::::      residue: 2 [spec: 1 "W" 105 ""]
:::::::::      residue: 3 [spec: 1 "A" 91 ""]
:::::::::      residue: 4 [spec: 1 "A" 47 ""]
:::::::::      residue: 5 [spec: 1 "A" 42 ""]
:::::::::      residue: 6 [spec: 1 "A" 41 ""]
:::::::::      residue: 7 [spec: 1 "A" 33 ""]
:::::::::      residue: 8 [spec: 1 "A" 82 ""]
:::::::::      residue: 9 [spec: 1 "A" 80 ""]
:::::::::      residue: 10 [spec: 1 "A" 63 ""]
:::::::::      residue: 11 [spec: 1 "A" 84 ""]
:::::::::      residue: 12 [spec: 1 "A" 35 ""]
:::::::::      residue: 13 [spec: 1 "A" 75 ""]
:::::::::      residue: 14 [spec: 1 "A" 24 ""]
:::::::::      residue: 15 [spec: 1 "A" 50 ""]
:::::::::      residue: 16 [spec: 1 "A" 59 ""]
:::::::::      residue: 17 [spec: 1 "A" 15 ""]
:::::::::      residue: 18 [spec: 1 "A" 16 ""]
:::::::::      residue: 19 [spec: 1 "A" 12 ""]
:::::::::      residue: 20 [spec: 1 "A" 76 ""]
::::::::: mol: 0x618c340
::::::::: name map size: 0
::::::::: water_dist_max: 3.25
::::::::: h_bond_dist_max: 3.9
DEBUG:: get_fle_ligand_bonds from h_bonds class found 1 H bonds.
DEBUG:: in get_fle_ligand_bonds() hbond [0] [spec: model 1 "W"  105 "" " O  " ""]...to... [spec: model 1 "L"   99 "" " O1 " ""] with ligand donor flag 0
constructing fle ligand bond  O1  0 2.6594 [spec: model 1 "W"  105 "" " O  " ""] HOH
.... get_fle_ligand_bonds(): after h-bonds v.size() is 1
.... get_fle_ligand_bonds(): after metal bonds v.size() is 1
:::: get_fle_ligand_bonds returns these 1 bonds: 
   0 :  Ligand-H-bond: 0 lig-at: [spec: model 1 "L"   99 "" " O1 " ""] [spec: model 1 "W"  105 "" " O  " ""] length: 3.8594 (water)
INFO:: LSQ matched 28 atoms
INFO:: 28 matched atoms had: 
   mean devi: 0.69973
    rms devi: 0.842458
    max devi: 2.16871
    min devi: 0.163807
INFO:: Success:: Minimum found at iter 407
```

**Comment by LanceWesterhoff** [comment]
Is there a version of Coot in which FLEV works? I can downgrade if required. Thanks!

**Comment by pemsley** [comment]
That looks like it's working. What make you thin that it failed? Do you get a window with a ligand in it?

**Comment by olegka96** [comment]
What makes me think so is that I do not see the interaction diagram. Instead, it opens the ligand builder window that I do not need. I also tried some previous Coot versions with the same result.

**Comment by LanceWesterhoff** [comment]
Hi Paul - apologies for the delay. I've asked @olegka96 to reply so I'm not paying middleman. 

As a note, I also don't see it in the homebrew-installed version of Coot.
Thanks for your help!

**Comment by olegka96** [comment]
Just to be clear. When I click Ligand->FLEV this residue I get this
![image](https://github.com/pemsley/coot/assets/15237080/be45247f-cccf-4b77-8f2c-f925b3ede85f)

Thus, I do not see any interaction diagrams I am keenly interested in.

**Comment by olegka96** [comment]
Hi Paul, 
I think we figured it out and were able to get the diagram.

**Comment by LanceWesterhoff** [comment]
Now that it would seem we figured out how to use it in Coot Release-0.9.8.92 we can close this out. 

@pemsley - I am trying to figure out how to use it in the homebrew (Mac) version, but it doesn't appear to be available yet as none of the modules (including Ligand) seem to load and none of the 2D views show the FLEV options. If I'm incorrect (and it should work) please reopen as you see fit. Thanks for your help!
