### ISSUE TITLE
Loss of cysteine connectivity information between mmcif and pdb formats.

### ISSUE THREAD

**Issue by TristynAlxander** [pemsley/coot#113]
In Coot version 0.9.8.7, when a `initial_structure.pdb` has the cystine connectivity information similar to the following format:

    SSBOND *** CYS A   51    CYS A   84 
    SSBOND *** CYS A   54    CYS A   71 
    SSBOND *** CYS A   61    CYS A   67 
    SSBOND *** CYS A   77    CYS A  101

If that file is opened in coot and saved as a `structure.mmcif` file this information is not stored. When `structure.mmcif` is opened in coot and saved as `final_structure.pdb` there is no cystine connectivity information. As a result refmac adds hydrogens in cysteine riding positions where a cystine should be present. 

I'm not familiar with mmcif format; however, if a syntax does not exist this information could be stored as a comment where `#SSBOND` is then found by the coot parser to preserve this structural information.

**Comment by TristynAlxander** [comment]
Alternatively, coot could check for connectivity before saving.

**Comment by pemsley** [comment]
OK, thanks, noted.
The solution, I think, to Coot's current failures at writing mmcifs is to use GEMMI. There will need to be some not-trivial infrastructure changes for this to happen and is not something for the short-term.

**Comment by TristynAlxander** [comment]
In Coot 0.9.8.95 this issue appears to have resurfaced backwards. I believe it's ignoring SSBOND information, which for nearby cystines sometimes causes the cysteines to jump out of the density and bond to another nearby cysteine. This happened in 0.9.8.7 for cif files and the fix was to convert to pdb and add the SSBOND information. In 0.9.8.95 it's ignoring the SSBOND information and I'm fixing the sulfur and manually centering it in the density.

**Comment by TristynAlxander** [comment]
In Coot 0.9.8.95,

Manual Placement:
![Image](https://github.com/user-attachments/assets/678f64fa-a5b4-4c2b-92af-405b072a6e5e)

Fit to Density Function:
![Image](https://github.com/user-attachments/assets/8ff0d632-4662-4559-a48d-7347b651600a)

Copy of SSBOND Section of pdb file:
```
SSBOND   1 CYS B   61    CYS B   91 
SSBOND   2 CYS B   81    CYS B  109 
SSBOND   3 CYS B  116    CYS B  135 
SSBOND   4 CYS B  122    CYS B  134 
SSBOND   5 CYS B  136    CYS B  141 
SSBOND   6 CYS D   61    CYS D   91 
SSBOND   7 CYS D   81    CYS D  109 
SSBOND   8 CYS D  116    CYS D  135 
SSBOND   9 CYS D  122    CYS D  134 
SSBOND  10 CYS D  136    CYS D  141 
```

In the program Cys 136 and Cys 91 seem to think they're bonded. I can't figure out why; though, I'll note that it's happening in phenix refine too. `ctrl` +`f`: `LINK` produces no results in the pdb file, so I don't think it's being specified elsewhere in the file. 

I can open a new issue if you like; though, I suspect this is connected to the original issue.
