### ISSUE TITLE
Updating Maps not working

### ISSUE THREAD

**Issue by asamkutty** [pemsley/coot#114]
Hi, 

The Updating Maps feature does not seem to be working (Calculate/Updating Maps --> select Auto Update). I can only get this to work for the tutorial data, but not for any models/maps outside of that. Currently, I load the pdb coordinates, then auto open the mtz file, import the CIF dictionary for my ligand, then go to Calculate/Updating Maps and select "Auto Update", but making a change to the model results in no change to the electron density map.

I checked the terminal after making a change and it says "DEBUG:: on_going_updating_map_lock was set! - aborting map update.", which could be a possible culprit, but I am not sure how to turn off the updating map lock (it doesn't come up under Calculate/Scripting/Python).

I ran this by Oliver Clarke, who was able to reproduce the issue on his end, and said the following:

"Yes I just took a look at this, and it is not working for me either. I see the following on first attempt to edit a model after enabling updating maps:

DEBUG:: watch_coordinates_updates() Update the map 1
DEBUG:: in fill_fobs_sigfobs() with have_sensible_refmac_params 0
DEBUG:: fill_fobs_sigfobs() no Fobs parameters
Original Fobs/sigFobs is not filled

And then the message you saw on any subsequent attempts.

This would seem to indicate there are no F/SigF columns, but when I take a look they are there, so I think it is a bug, worth reporting!"
 

Software details:
- Coot 0.9.8.91 EL (ccp4)
- Mac OS (monterey vs 12.6.5)

Please let me know if there is any other information I can share that would be useful. 

Thanks!

**Comment by pemsley** [comment]
It isn't a bug.  You haven't told Coot where to find the data.

Use the Column Selector dialog to tell Coot where to find Fobs and Fcalc and R-free 
"Assign Labels for Structure Factor Calculation"

**Comment by asamkutty** [comment]
Great, this works -- thank you for the clarification!

**Comment by pemsley** [comment]
The interface could be improved.
