### ISSUE TITLE
Trouble with adding alt conformations

### ISSUE THREAD

**Issue by KevGuy14** [pemsley/coot#123]
Hi everyone, 

I am a college undergraduate student who is brand new to both coot and protein structural modeling. I was able to get coot 1.1.03 installed on my Mac, but the version is different from the one that my mentor is using and is familiar with (I think 0.9.8). In trying to teach me how to effectively navigate the program, he tried to walk me through adding an alternative conformation to particular residue that looked like it may have occupancy in two different positions. However, the option to add an alt conformation does not appear on the right-hand menu in my version as it does in his, and neither of us were able to find the option after searching through the different menus. I spent some time looking online and was not able to find anything on this either. I know this is probably a very simple solution that I am just missing, but I really appreciate any help!

**Comment by pemsley** [comment]
Coot 1 is "Select First" i.e. you position the thing you want to act on (by bringing it to the centre of the screen) and then choose the modelling tool.
Like Minecraft.
It's better.

If you wish, the Coot that is distributed by CCP4 acts like your mentor expects it to act.

**Comment by KevGuy14** [comment]
Okay, that makes sense! In the meantime, I may try to get the CCP4 version. Thank you!
