### ISSUE TITLE
build-it-3-3 on Ubuntu 22.04

### ISSUE THREAD

**Issue by sayurlinux** [pemsley/coot#124]
Hello,
I tried to install Coot 1.x on Ubuntu 22.04 using the [build-it-3-3](https://raw.githubusercontent.com/pemsley/coot/main/build-it-3-3) script and it halted during coot build step (complete logs attached, partial shown below):

[build-gtk4.log](https://github.com/pemsley/coot/files/14489820/build-gtk4.log):
```
...
BUILDING guile-cairo
guile-lib needs to be installed
some test here  
guile-config found
not building guile-lib:
guile-gnome-platform skip_this false
BUILDING gnome-gnome-platform
BUILDING gnome-gnome-platform finished
GITHUB_WORKSPACE is
BUILDING coot
coot build failed, exiting.
```

[30-coot.txt](https://github.com/pemsley/coot/files/14489828/30-coot.txt):
```
...
checking for GSL - version >= 1.3... yes
checking for glm >= 0.9.9... no
configure: error: Package requirements (glm >= 0.9.9) were not met:

No package 'glm' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GLM_CFLAGS
and GLM_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No targets specified and no makefile found.  Stop.
=== make again ===
make: *** No targets specified and no makefile found.  Stop.
make failed.
```
So it can't find glm, but [17-glm.txt](https://github.com/pemsley/coot/files/14489858/17-glm.txt) exists and so do the following files/folders (among others it says has been installed):
```
~/autobuild/building/sources/glm-1.0.0.tar.gz
~/autobuild/building/JTEM-SBS_2024-03-05__T02_25_44/glm-1.0.0/
~/autobuild/Linux-JTEM-SBS-gtk4/lib/libglm.a
~/autobuild/Linux-JTEM-SBS-gtk4/include/glm/libglm.a
```

However, `~/autobuild/Linux-JTEM-SBS-gtk4/lib/x86_64-linux-gnu/pkgconfig/glm.pc` does not exist 
```
jtem@JTEM-SBS:~$ ls ~/autobuild/Linux-JTEM-SBS-gtk4/lib/x86_64-linux-gnu/pkgconfig/
gobject-introspection-1.0.pc  gobject-introspection-no-export-1.0.pc  py3cairo.pc  pygobject-3.0.pc
```
Is this why it can't find glm? I'm guessing the .pc file is needed to point pkgconfig to the autobuild files? I couldn't find where or how the .pc file is generated, this is as far as I can dig. 
Or maybe I am missing something?

Thanks in advance!

**Comment by pemsley** [comment]
@sayurlinux 
Hi. I don't know. I am disappointed that it didn't run through without error. I will have a think.

**Comment by pemsley** [comment]
`glm.pc` should have been installed in `~/autobuild/Linux-penelope-gtk4-jul-2023-gtk4/lib/x86_64-linux-gnu/pkgconfig/glm.pc`
was it for you?

**Comment by sayurlinux** [comment]
I don't see any mention of pkg-config in [17-glm.txt](https://github.com/pemsley/coot/files/14503539/17-glm.txt), unlike in `19-gobject-introspection.txt` or `07g-pygobject.txt`.

**Comment by sayurlinux** [comment]
Looking at [https://github.com/g-truc/glm](https://github.com/g-truc/glm), it seems pkg-config was added in version 0.9.7.6 and removed [here](https://github.com/g-truc/glm/commit/5f352ecce21bb1ab37fa56fac0f383c779b351a3)?

**Comment by pemsley** [comment]
> and removed [later on](https://github.com/g-truc/glm/commit/5f352ecce21bb1ab37fa56fac0f383c779b351a3)?

Oh yes! you are right - good spot.

But... oh no!

That is a backward step it seems to me.

**Comment by pemsley** [comment]
> I'm stuck now because 07-g-gettext.txt doesn't say anything about libintl.a

I am impressed with your skills! Yes, this is where I am stuck on the MacOS build (using gettext was a recent addition to try to resolve those problems).

**Comment by pemsley** [comment]
OK, I've updated `build-it-3-3`. Please give it another try.

**Comment by sayurlinux** [comment]
RDkit build doesn't give out errors anymore, and coot build stopped at glm as before. 

> But... oh no! That is a backward step it seems to me.

Yes I also scratched my head at that

If I use glm 0.9.9.5 instead, the build was successful and it runs!

Thank you very very much!!

PS: the doom reference is cool

**Comment by pemsley** [comment]
I will change the glm versin back to 0.9.9.5. Thanks.
