### ISSUE TITLE
 undefined reference to `cairo_*'

### ISSUE THREAD

**Issue by GuShaocheng** [pemsley/coot#133]
Hi,
It seems there are many undefined references related to cairo when building coot. Please see below. Any idea about that? Thanks! PS: I used build-it-3-3 on Ubuntu22.04.

/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_paint'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_show_text'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_surface_status'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_rectangle'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_set_font_size'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_rotate'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_save'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_image_surface_create'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_stroke'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_image_surface_create_for_data'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_move_to'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_restore'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_surface_write_to_png_stream'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_set_source_rgb'
/usr/bin/ld: /opt/cryoem/coot/build-coot/coot-utils/.libs/libcoot-coord-utils.so: undefined reference to `cairo_create'
/usr/bin/ld

**Comment by pemsley** [comment]
Thanks. Should be fixed in 6e8a932aec5826f4957fcd64d31f0a18f9d72ae5
i.e. git it another try now.

**Comment by GuShaocheng** [comment]
Thank you very much. It solved the issue, and coot can be build now.
