### ISSUE TITLE
Rama HUD in chain refine - interactive?

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#145]
Hi,

The ramachandran HUD in chain refine is very nice (in 1.1.08). It would be useful I think if it was interactive, so that one could click on outliers to navigate to them and fix them.

Cheers
Oli
<img width="364" alt="image" src="https://github.com/user-attachments/assets/992b3bd6-376f-44d5-b2b1-a2723f7ced3a">

**Comment by pemsley** [comment]
Yeah.

Somehow it wasn't on my list (or maybe it is - but so far down that I never see it).

OK. Noted.

**Comment by pemsley** [comment]
Done.
