### ISSUE TITLE
clipper update related to reading ccp4 maps in mode 0

### ISSUE THREAD

**Issue by wojdyr** [pemsley/coot#15]
@pemsley et al:
we made a small change in clipper today, after consulting Kevin:
http://fg.oisin.rc-harwell.ac.uk/scm/loggerhead/clipper/trunk/revision/340
Please consider updating.
(I'm experimenting with mode 0 maps because the files are 4x smaller)

**Comment by pemsley** [comment]
On 4 July 2016 at 20:07, Marcin Wojdyr <notifications@github.com> wrote:

> @pemsley <https://github.com/pemsley> et al:
> we made a small change in clipper today, after consulting Kevin:
> http://fg.oisin.rc-harwell.ac.uk/scm/loggerhead/clipper/trunk/revision/340
> Please consider updating.
>

The change will be rolled in when clipper* gets updated in
ftp://ftp.ccp4.ac.uk/opensource.

Paul.

**Comment by wojdyr** [comment]
I've just uploaded it:
ftp://ftp.ccp4.ac.uk/opensource/clipper-2.1.20160708.tar.gz

**Comment by pemsley** [comment]
thanks.
