### ISSUE TITLE
Rainbow ribbons are not rainbow

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#157]
e.g. for tutorial model:

<img width="945" alt="image" src="https://github.com/user-attachments/assets/39924666-9361-4c0d-b9b5-1ad03ab3c364">

Also, if I have a ribbon model displayed, but no atomic model, and then try to add another ribbon representation (e.g. sec struc or by chain), nothing happens. I guess it is expecting an atomic model to be displayed, but if so it should produce an error or warning indicating this to the user?

Also, once representations are created, I can undisplay them, but can't find a way to delete them - the entry in the representations window seems to remain no matter what I do. I expected that deleting generic display objects would delete these too, but it doesn't:

<img width="665" alt="image" src="https://github.com/user-attachments/assets/4f09efa8-f01e-4dc3-8ad0-91439ea57efc">

**Comment by pemsley** [comment]
Thanks.
Fixed in 7ac9aaca8b2128ecb40239e0639bbaf361bb40f0
