### ISSUE TITLE
coot-1.1.10, flev.hh/cc compilation failure

### ISSUE THREAD

**Issue by g1g0** [pemsley/coot#159]
Hello,
After a successful configure (with RDKIT_LIBS adjusted to the current debian sid), the compilation fails at pli/flev.hh and thus at pli/flev.cc. I tried to compile with gcc-11 and gcc-14, using the system-installed libraries (not build-it). It went like this:
./configure --with-rdkit-prefix=/usr <== all dependencies found, OK
make <== the compilation goes well up to the MoleculesToTriangles directory. Then:

Making all in pli
make[1]: Entering directory '/home/gigo/coot-1.1.10/pli'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"coot\" -DPACKAGE_TARNAME=\"coot\" -DPACKAGE_VERSION=\"1.1.10\" -DPACKAGE_STRING=\"coot\ 1.1.10\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"coot\" -DVERSION=\"1.1.10\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_OPENMP=1 -DHAVE_CXX11=1 -DHAVE_CXX_THREAD=1 -DHAVE_LIBM=1 -DHAVE_LIBGSLCBLAS=1 -DHAVE_LIBGSL=1 -DHAVE_PYTHON=\"3.12\" -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_THREAD=/\*\*/ -DHAVE_BOOST_PYTHON=/\*\*/ -I.  -DUSE_PYTHON -I..  -DCLIPPER_HAS_TOP8000 -DMMDB_HAS_LINK_DISTANCE -I/usr/include/python3.12 -I/usr/include/rdkit -DRDKIT_HAS_CAIRO_SUPPORT -pthread -I/usr/include    -g -O2 -Wall -Wno-unused  -std=c++17 -MT flev.lo -MD -MP -MF .deps/flev.Tpo -c -o flev.lo flev.cc
libtool: compile:  g++ -DPACKAGE_NAME=\"coot\" -DPACKAGE_TARNAME=\"coot\" -DPACKAGE_VERSION=\"1.1.10\" "-DPACKAGE_STRING=\"coot 1.1.10\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"coot\" -DVERSION=\"1.1.10\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_OPENMP=1 -DHAVE_CXX11=1 -DHAVE_CXX_THREAD=1 -DHAVE_LIBM=1 -DHAVE_LIBGSLCBLAS=1 -DHAVE_LIBGSL=1 -DHAVE_PYTHON=\"3.12\" "-DHAVE_BOOST=/**/" "-DHAVE_BOOST_THREAD=/**/" "-DHAVE_BOOST_PYTHON=/**/" -I. -DUSE_PYTHON -I.. -DCLIPPER_HAS_TOP8000 -DMMDB_HAS_LINK_DISTANCE -I/usr/include/python3.12 -I/usr/include/rdkit -DRDKIT_HAS_CAIRO_SUPPORT -pthread -I/usr/include -g -O2 -Wall -Wno-unused -std=c++17 -MT flev.lo -MD -MP -MF .deps/flev.Tpo -c flev.cc  -fPIC -DPIC -o .libs/flev.o
In file included from flev.cc:4:
flev.hh:18:26: error: ‘svg_atom_t’ was not declared in this scope
   18 |    lig_build::molecule_t<svg_atom_t, svg_bond_t> mol;
      |                          ^~~~~~~~~~
flev.hh:18:38: error: ‘svg_bond_t’ was not declared in this scope
   18 |    lig_build::molecule_t<svg_atom_t, svg_bond_t> mol;
      |                                      ^~~~~~~~~~
flev.hh:18:48: error: template argument 1 is invalid
   18 |    lig_build::molecule_t<svg_atom_t, svg_bond_t> mol;
      |                                                ^
flev.hh:18:48: error: template argument 2 is invalid
flev.hh:185:59: error: ‘svg_atom_t’ was not declared in this scope
  185 |                               const lig_build::molecule_t<svg_atom_t, svg_bond_t> &mol);
      |                                                           ^~~~~~~~~~
flev.hh:185:71: error: ‘svg_bond_t’ was not declared in this scope
  185 |                               const lig_build::molecule_t<svg_atom_t, svg_bond_t> &mol);
      |                                                                       ^~~~~~~~~~
flev.hh:185:81: error: template argument 1 is invalid
  185 |                               const lig_build::molecule_t<svg_atom_t, svg_bond_t> &mol);
      |                                                                                 ^
flev.hh:185:81: error: template argument 2 is invalid
flev.cc: In member function ‘bool flev_t::annotate(const std::vector<std::pair<coot::atom_spec_t, float> >&, const std::vector<pli::fle_residues_helper_t>&, const std::vector<int>&, const std::vector<pli::fle_ligand_bond_t>&, const std::vector<pli::solvent_exposure_difference_helper_t>&, const pli::flev_attached_hydrogens_t&, const pli::pi_stacking_container_t&, const coot::dictionary_residue_restraints_t&)’:
flev.cc:158:74: error: ‘svg_atom_t’ was not declared in this scope
  158 |    auto map_solvent_accessibilities_to_atoms = [] (lig_build::molecule_t<svg_atom_t, svg_bond_t> *new_mol_p,

and the resulting errors coming from svg_atom_t and svg_bond_t in flev.cc keep rolling till the very end.
I would be grateful for any suggestions on how to proceed. If you think it is a real error and want me to contribute, please let me know.
Best,
g

**Comment by pemsley** [comment]
David Taylor recently brought this problem to my attention. I will fix it for the next release.

For the moment, please use `--with-enhanced-ligand-tools` as a command line argument to `configure`

You will need to recompile from scratch, `make clean`.
