### ISSUE TITLE
moved-atom.hh missing on github

### ISSUE THREAD

**Issue by balducci** [pemsley/coot#175]
hello

while building latest master (62ea80197126256ca0c49bf1584428dee02168de) I get:

```
In file included from coot-molecule.cc:38:
coot-molecule.hh:80:10: fatal error: moved-atom.hh: No such file or directory
   80 | #include "moved-atom.hh"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:801: coot-molecule.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
```

Indeed, I cannot find the ``moved-atom.hh`` header in the cloned repository: forgot to push it on github or...?

ciao

gabriele

**Comment by pemsley** [comment]
Fixed in f7d26b5492f9f853fc6ec4a4f5c74ba69ff88153 and bb82b75aba7debac979f1a33c959516f14e8dc33.

Sorry for the inconvenience.
