### ISSUE TITLE
Coot vs WinCoot performance

### ISSUE THREAD

**Issue by hwalinga** [pemsley/coot#18]
Hello, 

This is just a question out of curiosity. 

I have a dual boot set up (Windows 10 and Linux Mint 17.3), and I installed Coot on both operating systems. (WinCoot and Ubuntu binary). 

I noticed that WinCoot performed much better than Coot when rotating and such. 

So, since hardware is equal, what do you think makes Coot on Linux so slow in comparison to WinCoot?

**Comment by pemsley** [comment]
I imagine that you are (were) using non-optimal, perhaps even software drivers for OpeGL on Ubuntu.
