### ISSUE TITLE
set_background_colour() not working in no-graphics mode

### ISSUE THREAD

**Issue by wojdyr** [pemsley/coot#19]
I'm using Coot in `--no-graphics` mode to generate screeshots (through Raster3D), as part of Dimple pipeline.
Trying to address ccp4/dimple#5 I tried calling set_background_colour() in a script, but apparently it's a no-op in no-graphics mode.

So could you enable changing of the background without graphical interface? For example, by moving these lines in set_background_colour() in src/c-interface.cc:

       g.background_colour[0] = red; 
       g.background_colour[1] = green; 
       g.background_colour[2] = blue; 

outside of `if (g.use_graphics_interface_flag) { ... }`.

**Comment by pemsley** [comment]
OK, fixed now. Thanks.
