### ISSUE TITLE
Refining/rotamer selection with two residues sharing alternative location?

### ISSUE THREAD

**Issue by ProustIdee** [pemsley/coot#26]
I have a PDB file where I built two residues with alternative locations:

    ATOM    939  N  AGLU E 199      33.272  31.560  33.627  0.50 48.23           N
    ATOM    940  CA AGLU E 199      31.862  31.570  34.004  0.50 51.70           C
    ATOM    941  C  AGLU E 199      31.478  30.325  34.793  0.50 53.08           C
    ATOM    942  O  AGLU E 199      30.501  30.348  35.552  0.50 54.33           O
    ATOM    943  CB AGLU E 199      30.983  31.710  32.762  0.50 54.36           C
    ATOM    944  CG AGLU E 199      30.991  33.098  32.143  0.50 58.52           C
    ATOM    945  CD AGLU E 199      30.216  33.153  30.844  0.50 70.32           C
    ATOM    946  OE1AGLU E 199      29.620  32.121  30.472  0.50 79.24           O
    ATOM    947  OE2AGLU E 199      30.202  34.219  30.191  0.50 65.14           O
    ATOM    948  N  BLYS E 199      33.272  31.568  33.624  0.50 48.22           N
    ATOM    949  CA BLYS E 199      31.860  31.572  33.998  0.50 51.73           C
    ATOM    950  C  BLYS E 199      31.480  30.328  34.793  0.50 53.08           C
    ATOM    951  O  BLYS E 199      30.511  30.355  35.561  0.50 54.30           O
    ATOM    952  CB BLYS E 199      30.984  31.689  32.750  0.50 54.33           C
    ATOM    953  CG BLYS E 199      30.965  33.079  32.120  0.50 58.59           C
    ATOM    954  CD BLYS E 199      30.195  33.075  30.806  0.50 70.40           C
    ATOM    955  CE BLYS E 199      30.262  34.425  30.102  0.50 66.17           C
    ATOM    956  NZ BLYS E 199      29.581  34.401  28.771  0.50 61.53           N

This is a crystal structure of a protein with a mutation where both residues are present at this position in the structure. This should be a valid, see "Site shared by several chemical moieties" under "typical occupancy refinement scenarios and available options in phenix.refine" here ( http://www.phenix-online.org/newsletter/CCN_2015_07.pdf ) or PDB 1EJG ( https://www.rcsb.org/structure/1EJG ).

Phenix has no issues with refinement, but Coot/Wincoot does not cooperate at all (even with allow_duplicate_sequence_numbers() set). I can pick rotamers for the BLYS, but when I hit "OK" it fails:

    Click on an atom in a residue for which you wish to see rotamers
    setup_rotamers (1)
    (0) " NZ ,B"/1/chainid="E"/199/LYS,  occ: 0.5 with B-factor: 61.53 element: " N" at (29.581,34.401,28.771) : 0.261882
    setup_rotamers (0)
    INFO:: backup file C:\WinCoot0893_7909\coot-backup/structure.pdb_Sat_Aug_10_10_18_39_2019_modification_1.pdb.gz
    WARNING:: full_atom_spec_to_atom_index() Could not find " N  ","B"/199/E in this molecule: (0) C:\Users\user\Documents\Xtal\structure.pdb
    DEBUG:: idx: -1
    ERROR:: failed to find atom in molecule: chain-id :E: res_no 199 inscode :: name : N  : altloc :B:
    ERROR:: bad atom index in replace_coords replacing atom: 1/E/199 {LYS}/ N   altLoc :B: segid :: pos: (33.272,31.568,33.624) B-factor: 48.22
    WARNING:: full_atom_spec_to_atom_index() Could not find " CA ","B"/199/E in this molecule: (0) C:\Users\user\Documents\Xtal\structure.pdb
    DEBUG:: idx: -1
    ERROR:: failed to find atom in molecule: chain-id :E: res_no 199 inscode :: name : CA : altloc :B:
    ERROR:: bad atom index in replace_coords replacing atom: 1/E/199 {LYS}/ CA  altLoc :B: segid :: pos: (31.86,31.572,33.998) B-factor: 51.73
    WARNING:: full_atom_spec_to_atom_index() Could not find " C  ","B"/199/E in this molecule: (0) C:\Users\user\Documents\Xtal\structure.pdb
    DEBUG:: idx: -1
    ERROR:: failed to find atom in molecule: chain-id :E: res_no 199 inscode :: name : C  : altloc :B:
    ERROR:: bad atom index in replace_coords replacing atom: 1/E/199 {LYS}/ C   altLoc :B: segid :: pos: (31.48,30.328,34.793) B-factor: 53.08
    WARNING:: full_atom_spec_to_atom_index() Could not find " O  ","B"/199/E in this molecule: (0) C:\Users\user\Documents\Xtal\structure.pdb
    DEBUG:: idx: -1
    ERROR:: failed to find atom in molecule: chain-id :E: res_no 199 inscode :: name : O  : altloc :B:
    ERROR:: bad atom index in replace_coords replacing atom: 1/E/199 {LYS}/ O   altLoc :B: segid :: pos: (30.511,30.355,35.561) B-factor: 54.3
    WARNING:: full_atom_spec_to_atom_index() Could not find " CB ","B"/199/E in this molecule: (0) C:\Users\user\Documents\Xtal\structure.pdb
    DEBUG:: idx: -1
    ERROR:: failed to find atom in molecule: chain-id :E: res_no 199 inscode :: name : CB : altloc :B:
    ERROR:: bad atom index in replace_coords replacing atom: 1/E/199 {LYS}/ CB  altLoc :B: segid :: pos: (30.984,31.689,32.75) B-factor: 54.33
    WARNING:: full_atom_spec_to_atom_index() Could not find " CG ","B"/199/E in this molecule: (0) C:\Users\user\Documents\Xtal\structure.pdb
    DEBUG:: idx: -1
    ERROR:: failed to find atom in molecule: chain-id :E: res_no 199 inscode :: name : CG : altloc :B:
    ERROR:: bad atom index in replace_coords replacing atom: 1/E/199 {LYS}/ CG  altLoc :B: segid :: pos: (31.1328,33.0073,31.9955) B-factor: 58.59
    WARNING:: full_atom_spec_to_atom_index() Could not find " CD ","B"/199/E in this molecule: (0) C:\Users\user\Documents\Xtal\structure.pdb
    DEBUG:: idx: -1
    ERROR:: failed to find atom in molecule: chain-id :E: res_no 199 inscode :: name : CD : altloc :B:
    ERROR:: bad atom index in replace_coords replacing atom: 1/E/199 {LYS}/ CD  altLoc :B: segid :: pos: (30.2293,33.0427,30.77) B-factor: 70.4
    WARNING:: full_atom_spec_to_atom_index() Could not find " CE ","B"/199/E in this molecule: (0) C:\Users\user\Documents\Xtal\structure.pdb
    DEBUG:: idx: -1
    ERROR:: failed to find atom in molecule: chain-id :E: res_no 199 inscode :: name : CE : altloc :B:
    ERROR:: bad atom index in replace_coords replacing atom: 1/E/199 {LYS}/ CE  altLoc :B: segid :: pos: (30.3983,34.3315,29.9743) B-factor: 66.17
    WARNING:: full_atom_spec_to_atom_index() Could not find " NZ ","B"/199/E in this molecule: (0) C:\Users\user\Documents\Xtal\structure.pdb
    DEBUG:: idx: -1
    ERROR:: failed to find atom in molecule: chain-id :E: res_no 199 inscode :: name : NZ : altloc :B:
    ERROR:: bad atom index in replace_coords replacing atom: 1/E/199 {LYS}/ NZ  altLoc :B: segid :: pos: (30.0017,35.5376,30.7642) B-factor: 61.53
    INFO:: replace_coords: 0 atoms updated.
    Model atom pick failed.

Sphere Refine+ doesn't even "see" the BLYS, and if I try to do a "Real Space Refine Zone", Wincoot crashes:

    calling update_refinement_atoms()
    gsl: ../gsl/gsl_vector_double.h:180: ERROR: index out of range
    Default GSL error handler invoked.

[Edit] Adding allow_duplicate_sequence_numbers() fixes the crash on "Real Space Refine Zone", but still doesn't allow any refinement or rotamer selection of BLYS.

**Comment by pemsley** [comment]
It doesn't crash now, but there is still a bug. Thanks.
