### ISSUE TITLE
refmac5 failed

### ISSUE THREAD

**Issue by bingwang14** [pemsley/coot#29]
Hi,

When I run a tutorial following "Coot Cryo-EM Tutorial 2: Fitting and Mutating", I met the error with warning info:"refmac5 failed".  It happened when I started "Multi-sharpen using Refmac" from the Cryo-EM modules. Here is the specific error messages. 
usage: refmac_window.py [-h] [--args Arguments] [--args_string Arguments]
                        [--job_location JOB_LOCATION] [--job_id JOB_ID]
                        [--project_location PROJECT_LOCATION] [--gui]
                        [--no-gui]
refmac_window.py: error: unrecognized arguments: MAPIN EMD-3908/map/emd_3908.map
(info-dialog "WARNING:: refmac5 failed")

Do you have any idea what is going on and how to fix it? Thank you.

Regards,
Bing

**Comment by pemsley** [comment]
Hello Bing,
I don't understand this. refmac_window.py is not part of Coot. I guess that the problem lies elsewhere.
(The info-dialog is part of Coot though.)
