### ISSUE TITLE
autobuilding failed

### ISSUE THREAD

**Issue by GuShaocheng** [pemsley/coot#30]
Hi Paul,

I downloaded the coot-0.9.2 and try to install it on ubuntu follow the suggestion from the INSTALL file, that is to use the auto-builder. I guess there are some problems between the scripts and website because the scripts cannot download the correct package of the coot.  Could you give me some advice to figure out it after you look through the output of the auto-builder.

Thank you very much.
###########
--2020-11-13 10:47:35--  http://skuld.bmsc.washington.edu/raster3d/Raster3D_3.0-3.tar.gz
Resolving skuld.bmsc.washington.edu (skuld.bmsc.washington.edu)... 128.95.235.53
Connecting to skuld.bmsc.washington.edu (skuld.bmsc.washington.edu)|128.95.235.53|:80... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘/home/uf/autobuild/building/sources/Raster3D_3.0-3.tar.gz’ not modified on server. Omitting download.

Makefile:7: Makefile.incl: Permission denied
make: *** No rule to make target 'Makefile.incl'.  Stop.
URL transformed to HTTPS due to an HSTS policy
--2020-11-13 10:47:36--  https://www2.mrc-lmb.cam.ac.uk/personal/pemsley/coot/source/releases/.tar.gz
Resolving www2.mrc-lmb.cam.ac.uk (www2.mrc-lmb.cam.ac.uk)... 131.111.85.100
Connecting to www2.mrc-lmb.cam.ac.uk (www2.mrc-lmb.cam.ac.uk)|131.111.85.100|:443... connected.
HTTP request sent, awaiting response... 300 Multiple Choices
Length: 629 [text/html]
Saving to: ‘/home/uf/autobuild/building/sources/.tar.gz’

.tar.gz                                      100%[==============================================================================================>]     629  --.-KB/s    in 0s      

Last-modified header missing -- time-stamps turned off.
2020-11-13 10:47:36 (22,6 MB/s) - ‘/home/uf/autobuild/building/sources/.tar.gz’ saved [629/629]

gzip: /home/uf/autobuild/building/sources/.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
###########

part attachment of the INSTALL file:
######
Building Automatically
----------------------

 I'd say that the easiest way to try to build coot is to use the
 auto-builder:

 https://raw.githubusercontent.com/pemsley/coot/master/build-it
######

**Comment by pemsley** [comment]
I've fixed up the INSTALL instructions - thanks.
