### ISSUE TITLE
The script build-it cannot download libccp4-6.5.1.tar.gz from ftp.ccp4.ac.uk

### ISSUE THREAD

**Issue by ckywong** [pemsley/coot#37]
In the script build-it, there is a wget command downloading libccp4-6.5.1.tar.gz from ftp.ccp4.ac.uk.

> ${WGET} ftp://ftp.ccp4.ac.uk/opensource/libccp4-$libccp4_version.tar.gz

The site ftp.ccp4.ac.uk has been inaccessible for many days.  The download eventually fails after 20 failed attempts.

> wget ftp://ftp.ccp4.ac.uk/opensource/libccp4-6.5.1.tar.gz
--2022-03-28 11:20:52--  ftp://ftp.ccp4.ac.uk/opensource/libccp4-6.5.1.tar.gz
           => ‘libccp4-6.5.1.tar.gz’
Resolving ftp.ccp4.ac.uk (ftp.ccp4.ac.uk)... 148.79.162.88
Connecting to ftp.ccp4.ac.uk (ftp.ccp4.ac.uk)|148.79.162.88|:21... failed: Connection timed out.
Retrying.
>
> --2022-03-28 11:23:04--  ftp://ftp.ccp4.ac.uk/opensource/libccp4-6.5.1.tar.gz
  (try: 2) => ‘libccp4-6.5.1.tar.gz’
Connecting to ftp.ccp4.ac.uk (ftp.ccp4.ac.uk)|148.79.162.88|:21... 

Can somebody please take a look?

Thank you!

**Comment by pemsley** [comment]
This dependency has been moved to LMB server now.
