### ISSUE TITLE
Multiple missing headers

### ISSUE THREAD

**Issue by jcbollinger** [pemsley/coot#42]
I'm attempting to build Coot 1 from the release tarball at https://www2.mrc-lmb.cam.ac.uk/personal/pemsley/coot/source/releases/coot-1.tar.gz.  After implementing a temporary workaround for issue #41, the build fails later, on account of a missing header:
```
In file included from meshed-generic-display-object.hh:12,
                 from coot-render.hh:15,
                 from molecule-class-info.h:80,
                 from graphics-info.h:79,
                 from main.cc:91:
Mesh.hh:10:10: fatal error: g_triangle.hh: No such file or directory
 #include "g_triangle.hh"
          ^~~~~~~~~~~~~~~
```
I don't find a header by that name anywhere in the source package or in this repository, and Google doesn't recognize it as a name from any common package.  Further investigation seems to indicate other missing headers, too: at least `map_triangle.hh` and `lights-info.hh`.

**Comment by pemsley** [comment]
Probably a good idea to keep your eye on the gtk3 commits: https://github.com/pemsley/coot/commits/gtk3
