### ISSUE TITLE
Rama HUD not interactive?

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#43]
Hi @pemsley,

I really like the new local Ramachandran overlay during RSR! Would it be possible to make the plot interactive, so we can click on and navigate to outliers? Or is it supposed to be like that already but not working on Mac yet?

Cheers
Oli

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/19766818/162072237-d72cea11-403a-4395-900c-185de7e5a734.png">

**Comment by pemsley** [comment]
The plot is supposed to be interactive. Try pressing the green arrow, btw - does that work?

**Comment by Species10C** [comment]
Oh thats what the Green arrow does! Ive been Clicking R/RC!

--

Playing around, I accidentally clicked on R/RC twice in a row. After I cannot dismiss the HUD by clicking Close and get

`(coot-bin:59868): Gtk-WARNING **: 17:28:40.592: Can't set a parent on widget which has a parent`

It looks like two HUD are superimposed on each other, but I can't dismiss either.

**Comment by pemsley** [comment]
> I would also maybe shift the restraints boxes that come up over to the left slightly - that way the green arrow can be used like a toggle (maybe switching from left arrow to right arrow on click?)

I like the idea - not sure how easy it will be to do though.

**Comment by pemsley** [comment]
@Species10C https://github.com/pemsley/coot/issues/43#issuecomment-1091881897 fixed in 1a85239a129e118102bba0062bb4704fe779bbf9
@olibclarke Rama plot points now clickable in resized windows in 1.0.03.
