### ISSUE TITLE
Compiling Coot

### ISSUE THREAD

**Issue by zxianren** [pemsley/coot#50]
when I run ./configure, Ifix the all error.
Then I type make , the error is up:
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DPACKAGE_NAME=\"coot\" -DPACKAGE_TARNAME=\"coot\" -DPACKAGE_VERSION=\"1.0.02\" -DPACKAGE_STRING=\"coot\ 1.0.02\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"coot\" -DVERSION=\"1.0.02\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_OPENMP=1 -DHAVE_CXX11=1 -DHAVE_CXX_THREAD=1 -DHAVE_PYTHON=\"3.8\" -DHAVE_BOOST=/\*\*/ -DHAVE_BOOST_PYTHON=/\*\*/ -I.     -g -O2 -Wall -Wno-unused  -std=c++11 -c -o getopt.lo getopt.cc
/bin/bash: ../depcomp: No such file or directory
make[1]: *** [Makefile:547: getopt.lo] Error 127
make[1]: Leaving directory '/home/paul/Documents/coot-1.0.02/compat'
make: *** [Makefile:723: all-recursive] Error 1

could you give me some ideas? Thanks so much!

**Comment by pemsley** [comment]
This is a problem with running configure - or maybe automake or autoconf I think. Are you using build-it-3-3?
If you wish to pursue this, let's see the output of configure.

**Comment by zxianren** [comment]
Thanks for your Reply.This is the output:

paul@ubuntu:~/Documents/coot-1.0.02$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/bin/bash: /home/paul/Documents/coot-1.0.02/missing: No such file or directory
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking for library containing strerror... none required
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) none
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking which libtool initialization strategy to adopt... AC-PROG-LIBTOOL
checking what warning flags to pass to the C compiler... -Wall -Wunused
checking what language compliance flags to pass to the C compiler... 
checking what warning flags to pass to the C++ compiler... -Wall -Wno-unused
checking what language compliance flags to pass to the C++ compiler... 
checking sys/stdtypes.h usability... no
checking sys/stdtypes.h presence... no
checking for sys/stdtypes.h... no
checking for OpenMP flag of C compiler... -fopenmp
checking whether g++ supports C++11 features by default... yes
checking for std::thread in thread... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GLIB... yes
checking if this is MINGW on Windows... no
checking if this is msys2 windows 64... no
checking for LIBPNG... yes
checking for CAIRO... yes
checking for SQLite3... no
checking for mmdb2... yes
checking for ssm... yes
no
checking for non-prefixed single-precision FFTW2 (fftw.h)... yes
checking for Clipper... yes
Not using guile
checking for gsl-config... no
checking for GSL - version >= 1.3... no
*** The gsl-config script installed by GSL could not be found
*** If GSL was installed in PREFIX, make sure PREFIX/bin is in
*** your path, or set the GSL_CONFIG environment variable to the
*** full path to gsl-config.
checking glm/glm.hpp usability... yes
checking glm/glm.hpp presence... yes
checking for glm/glm.hpp... yes
checking for GTK... yes
checking for GOOCANVAS... yes
checking for a Python interpreter with version >= 3.7... python3
checking for python3... /usr/bin/python3
checking for python3 version... 3.8
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3/dist-packages
checking for python3 extension module directory... ${exec_prefix}/lib/python3/dist-packages
checking for python3.8... (cached) /usr/bin/python3
checking for a version of Python >= '2.1.0'... yes
checking for the distutils Python package... yes
checking for Python include path... -I/usr/include/python3.8
checking for Python library path... -L/usr/lib -lpython3.8
checking for Python site-packages path... /usr/lib/python3/dist-packages
checking python extra libraries... -lcrypt -lpthread -ldl  -lutil -lm -lm
checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
checking consistency of all components of python development environment... yes
checking for boostlib >=  (102000)... yes
checking whether the Boost::Python library is available... yes
checking whether boost_python is the correct library... no
checking whether boost_python38 is the correct library... yes
ENHANCED_LIGAND_TOOLS_CPPFLAGS
Not using MySQL database
checking for curl >= 7.9.7... FAILED
configure: WARNING: curl-config was not found
checking build type... Linux-x86_64-ubuntu-20.04.3gtk3
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating macros/Makefile
config.status: creating pdb-templates/Makefile
config.status: creating scheme/Makefile
config.status: creating python/Makefile
config.status: creating compat/Makefile
config.status: creating utils/Makefile
config.status: creating coot-utils/Makefile
config.status: creating protein_db/Makefile
config.status: creating ccp4mg-utils/Makefile
config.status: creating coords/Makefile
config.status: creating db-main/Makefile
config.status: creating density-contour/Makefile
config.status: creating angles/Makefile
config.status: creating mini-mol/Makefile
config.status: creating skeleton/Makefile
config.status: creating ligand/Makefile
config.status: creating geometry/Makefile
config.status: creating ideal/Makefile
config.status: creating build/Makefile
config.status: creating analysis/Makefile
config.status: creating high-res/Makefile
config.status: creating tw/Makefile
config.status: creating cootaneer/Makefile
config.status: creating cootilus/Makefile
config.status: creating greg-tests/Makefile
config.status: creating python-tests/Makefile
config.status: creating lidia-core/Makefile
config.status: creating goograph/Makefile
config.status: creating lbg/Makefile
config.status: creating doc/Makefile
config.status: creating src/Makefile
config.status: creating src/coot
config.status: creating python/coot_load_modules.py
config.status: creating data/Makefile
config.status: creating data/rama-coeffs/Makefile
config.status: creating data/metal/Makefile
config.status: creating data/cho-models/Makefile
config.status: creating data/cho-acedrg/Makefile
config.status: creating glTF/Makefile
config.status: creating pixmaps/Makefile
config.status: creating pixmaps/icons/Makefile
config.status: creating textures/Makefile
config.status: creating rama-data/Makefile
config.status: creating man/Makefile
config.status: creating pli/Makefile
config.status: creating fonts/Makefile
config.status: creating pyrogen/Makefile
config.status: creating pyrogen/pyrogen
config.status: creating auxil/Makefile
config.status: creating auxil/catcheck/Makefile
config.status: creating auxil/rama/Makefile
config.status: creating auxil/sec-str/Makefile
config.status: creating auxil/strand-analysis/Makefile
config.status: creating auxil/vectors/Makefile
config.status: creating rcrane/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands

**Comment by pemsley** [comment]
@zxianren https://github.com/pemsley/coot/issues/50#issuecomment-1097716154 See build-it-3-3 for an example of the arguments to pass to coot's configure (towards the end of the file). Please try with 1.0.04.
