### ISSUE TITLE
1.0.02 crashes while loading an mrc file

### ISSUE THREAD

**Issue by jmcdonal** [pemsley/coot#51]
Hi, 
I have compiled version  1.0.02 but I'm seeing some startup errors on my system and the coot program crashes when I try to open an map/mrc file.   The messages from the startup and the crash happens just as I open the mrc file.    I can provide a core file, if that is helpful. 
Regards,
Jeff

$ coot 
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib64/python3.9/abc.py", line 85, in <module>
ModuleNotFoundError: No module named '_abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/io.py", line 52, in <module>
  File "/usr/lib64/python3.9/abc.py", line 89, in <module>
  File "/usr/lib64/python3.9/_py_abc.py", line 35
    def __new__(mcls, name, bases, namespace, /, **kwargs):
                                              ^
SyntaxError: invalid syntax
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib64/python3.9/abc.py", line 85, in <module>
ModuleNotFoundError: No module named '_abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/io.py", line 52, in <module>
  File "/usr/lib64/python3.9/abc.py", line 89, in <module>
  File "/usr/lib64/python3.9/_py_abc.py", line 35
    def __new__(mcls, name, bases, namespace, /, **kwargs):
                                              ^
SyntaxError: invalid syntax
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib64/python3.9/abc.py", line 85, in <module>
ModuleNotFoundError: No module named '_abc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.9/io.py", line 52, in <module>
  File "/usr/lib64/python3.9/abc.py", line 89, in <module>
  File "/usr/lib64/python3.9/_py_abc.py", line 35
    def __new__(mcls, name, bases, namespace, /, **kwargs):
                                              ^
SyntaxError: invalid syntax

(coot-bin:2364677): Gtk-CRITICAL **: 10:31:28.411: gtk_menu_item_set_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed
DEBUG:: setting OpenGL required version to 3 3
OOPS:: on_glarea_realize() error on gtk_gl_area_make_current()
Coot Python Scripting GUI code found and loaded.

(coot-bin:2364677): Gtk-CRITICAL **: 10:31:42.555: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
Gtk-Message: 10:31:42.555: GtkDialog mapped without a transient parent. This is discouraged.
INFO:: map file type was determined to be CCP4 type
DEBUG:: init xmap with P 1  Cell (633597,633597,     0,    90,    90,    90) Nuvw = (2048,2048,   1)
/panfs/hisoftware/cryoem/coot/1.0.02/bin/coot: line 229: 2364677 Segmentation fault      (core dumped) $coot_bin "$@"
. ------ Coot crashed - trying to diagnose -----

**Comment by pemsley** [comment]
> File "/usr/lib64/python3.9/abc.py", line 85, in
> ModuleNotFoundError: No module named '_abc'

This look it might be compiling or configuring with one version of python but executing with another.

**Comment by jmcdonal** [comment]
OK, thanks I found indeed that RHEL/Rocky 8.5 the runtime version was using python3.6 and I compiled with 3.9, I think I fixed that and my python errors are gone but its still crashing when I try to load a map file:  

$ coot 

(coot-bin:2412287): Gtk-CRITICAL **: 08:35:31.621: gtk_menu_item_set_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed
DEBUG:: setting OpenGL required version to 3 3
OOPS:: on_glarea_realize() error on gtk_gl_area_make_current()
Coot Python Scripting GUI code found and loaded.

(coot-bin:2412287): Gtk-CRITICAL **: 08:35:48.537: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
Gtk-Message: 08:35:48.538: GtkDialog mapped without a transient parent. This is discouraged.
INFO:: map file type was determined to be CCP4 type
DEBUG:: init xmap with P 1  Cell (631619,631619,     0,    90,    90,    90) Nuvw = (2048,2048,   1)
/panfs/hisoftware/cryoem/coot/1.0.02/bin/coot: line 229: 2412287 Segmentation fault      (core dumped) $coot_bin "$@"
. ------ Coot crashed - trying to diagnose -----

**Comment by pemsley** [comment]
>  DEBUG:: init xmap with P 1 Cell (631619,631619, 0, 90, 90, 90) Nuvw = (2048,2048, 1)

This is not a typical CCP4 map. Does it work with Coot 0.9.x? Does it work with a more conventional CCP4 map?

**Comment by jmcdonal** [comment]
I'm not an expert in the crystallography field, i'm helping with the software builds.   The researcher says that this map file worked with 0.9.8.    Do you have somewhere some test data I can try?  Or do you have automated tests that I can use to verify the build?

**Comment by pemsley** [comment]
I see. Has the map been written by an Intel processor and being read by Apple Silicon (or some such)? Or is it the same computer running Coot 1 as it does Coot 0.9.8?

**Comment by jmcdonal** [comment]
Hi Paul,  
I found that I was trying to open an incorrect mrc file--one that was too raw to be used.   I have one from postprocessing now but I'm still seeing a crash, do you know what can cause the assertion failure below?  

I have confirmed that this mrc file opens with coot 0.9.8. 

Thanks,
Jeff
$ coot 

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.443: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.443: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.480: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.481: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.510: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.511: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.566: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.566: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.651: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.652: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.714: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.714: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.775: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.775: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.814: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.815: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.843: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.843: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.880: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.880: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.922: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-WARNING **: 10:48:49.922: Content added to the action area of a dialog using header bars

(coot-bin:3145244): Gtk-CRITICAL **: 10:48:49.981: gtk_menu_item_set_submenu: assertion 'GTK_IS_MENU_ITEM (menu_item)' failed
DEBUG:: setting OpenGL required version to 3 3
OOPS:: on_glarea_realize() error on gtk_gl_area_make_current()
Coot Python Scripting GUI code found and loaded.
Gtk-Message: 10:49:04.313: GtkDialog mapped without a transient parent. This is discouraged.
INFO:: map file type was determined to be CCP4 type
DEBUG:: init xmap with P 1  Cell (341.376,341.376,341.376,    90,    90,    90) Nuvw = ( 384, 384, 384)
INFO:: map read 1010 milliseconds
-0.0974933        8  
-0.0853617       31  
-0.0732301      163  
-0.0610985      767  
-0.0489669     2874  
-0.0368352     9696  
-0.0247036    48889  
 -0.012572  2155368  *******************
-0.00044042  51586122  ****************************************************************************************************|
 0.0116912  2618150  ***********************
 0.0238228   137937  *
 0.0359544    37760  
  0.048086    14368  
 0.0602176     6203  
 0.0723492     2804  
 0.0844808     1210  
 0.0966124      511  
  0.108744      189  
  0.120876       41  
  0.133007       13  
  0.145139        0  
Pre-filter Map statistics: mean: 2.10109e-05 st.d: 0.00389757
Pre-filter Map statistics:  min: -0.103559 max: 0.139073
INFO:: n grid points:             56623104
INFO:: mean before filtering:     2.10109e-05
INFO:: variance before filtering: 1.5191e-05
INFO:: filter by ignoring 1065119 of 56623104 counts ( = 1.881%) with values around 3.271e-05 bounds 2.058e-05 4.484e-05 from bin-number 4269 of 10000
Post-filter Map statistics: mean: 2.078e-05 st.d: 0.003935
Post-filter Map statistics: min: -0.1036 max: 0.1391
INFO:: map_density_distribution() took 537 milliseconds
-------------------------  em 1 contour_level 0.01771
      Map extents: ..... 384 384 384 
      Map mean: ........ 2.078e-05
      Map rmsd: ........ 0.003935
      Map maximum: ..... 0.1391
      Map minimum: ..... -0.1036
coot-bin: ../src/dispatch_common.c:858: epoxy_get_proc_address: Assertion `0 && "Couldn't find current GLX or EGL context.\n"' failed.
/panfs/hisoftware/cryoem/coot/1.0.03/bin/coot: line 229: 3145244 Aborted                 (core dumped) $coot_bin "$@"
. ------ Coot crashed - trying to diagnose -----

**Comment by pemsley** [comment]
@jmcdonal https://github.com/pemsley/coot/issues/51#issuecomment-1104101608 Are you running coot remotely or some such? Please configure with --backward and --with-libdw and recompile (from scratch). You may need to install libdw beforehand. The subsequent crash report will give me a lot more to work with. Thanks.

**Comment by jmcdonal** [comment]
Hi,
I am running it remotely but via Enginframe/nice/dcv, so all the
graphics processing should be performed on the remote server.
jeff

On Wed, Apr 20, 2022 at 11:57 AM Paul Emsley ***@***.***> wrote:
>
> @jmcdonal #51 (comment) Are you running coot remotely or some such? Please configure with --backward and --with-libdw and recompile (from scratch). You may need to install libdw beforehand. The subsequent crash report will give me a lot more to work with. Thanks.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>



-- 

Jeffrey McDonald, PhD
Director of Information Technology
The Hormel Institute
801 16th Ave NE            email: ***@***.***
Austin, MN 55912           phone: +1 507.437.9654

**Comment by jmcdonal** [comment]
I'm using release 1.0.03, I can use the github repo but which branch should I use?  gtk3?

**Comment by pemsley** [comment]
@jmcdonal https://github.com/pemsley/coot/issues/51#issuecomment-1104413295 Yes, gtk3.
