### ISSUE TITLE
Use() called for unset Shader

### ISSUE THREAD

**Issue by jcbollinger** [pemsley/coot#53]
Coot 1 (gtk3) emits the following diagnostic at startup:

    GL ERROR:: --------------------------------- ooops Use() called for unset Shader

This appears to be coming from `graphics_info_t::setup_draw_for_anchored_atom_markers_init()`, and therefore to be related to `graphics_info_t::shader_for_anchored_atom_markers`.  That is consistent with the absence of any call to that shader's `init()` method.

**Comment by pemsley** [comment]
Fixed in 5300e44655f5e0b5cd48594a743607a69d3a3c52 (1.0.04)
