### ISSUE TITLE
renumber residue panel is missing chain selection

### ISSUE THREAD

**Issue by Species10C** [pemsley/coot#54]
The Renumber Residue panel is missing:
-dropdown menu for the chain
-the ability to specify the terminal residue to which the range should apply to

![image](https://user-images.githubusercontent.com/102914854/162918065-b24ea747-7383-4f61-8bd6-583713101eb5.png)

**Comment by pemsley** [comment]
Fixed in 56e52907bd12f67e9df5f4d3c6f097551c851012 and will be available in 1.0.05.
