### ISSUE TITLE
Boost libraries and headers not found

### ISSUE THREAD

**Issue by jcbollinger** [pemsley/coot#55]
While building Coot 1 on a machine that did not have Boost libraries or headers installed in the standard search paths, I found that configuring with `--with-boost=/path/to/boost/headers --with-boost-libdir=/path/to/boost/libraries` was not sufficient for a successful build.  Some Coot components built successfully, which seems to show that I provided correct configuration options, but others did not see the boost headers and / or libraries.  It looks like the needed flags variables were not inserted into the `Makefile.am` files in some of the places where they are needed.

This issue does not appear to be new, but it likely will not have manifested in build environments where Boost is installed in the standard search paths.  It is potentially pernicious in such environments, however, for if a different Boost implementation than the default one is specified via `configure` arguments, such as the `build-it` script will do, then Coot can end up being built against a mixture of different Boost versions.

A pull request will be forthcoming soon.

**Comment by pemsley** [comment]
Thanks, I can't pull (yet). I read the diffs though and made what I think are effectively the same changes.
