### ISSUE TITLE
Ramachandran HUD in rotamer selector?

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#59]
Hi Paul,

When I use the rotamer selection interface, a HUD appears which I think shows the ramachandran plot (although in some kind of density format, no discrete residues shown). This plot is the same no matter which residue I center on, so it doesn't appear to be some kind of local metric. Is this a placeholder? Maybe a rotamer probability graph of some description would be useful here?

Cheers
Oli

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/19766818/166943186-3b262a26-ff53-46e5-81d6-200cfe1c0ab1.png">

**Comment by pemsley** [comment]
Thanks - fixed in bc0c00d94f75ecdf71cfa22e4814de4f5930940b
