### ISSUE TITLE
Build-it-3-3 also fails on a fresh installation of fedora 36

### ISSUE THREAD

**Issue by murpholinox** [pemsley/coot#62]
After doing...

1. `wget https://raw.githubusercontent.com/pemsley/coot/gtk3/build-it-3-3`
2. `sudo dnf install g++ patch cmake python3-pip guile-devel` 
3. `bash build-it-3-3` 

it fails with `ls: cannot access '/home/murph/autobuild/Linux-fedora-gtk3/lib/python3.9/site-packages/numpy-*/numpy/lib/_version.py': No such file or directory` ... 

`/home/murph/autobuild/Linux-fedora-gtk3/lib/python3.9/site-packages` exists with a `README.txt` file only... 

Thanks

**Comment by cemcv25** [comment]
I believe you need to install gfortran to compile numpy, this error was fixed when I installed gfortran on Ubuntu 22.04 and then build-it-3-3 worked
