### ISSUE TITLE
build-it-3-3 fails with CentOS 7.9

### ISSUE THREAD

**Issue by DHouldershaw** [pemsley/coot#63]
Hi,
 As per issue #57 the script runs but exits with  coot build failed, exiting. Looking at the build logs, particularly 30-coot.txt, there is a number of compilation errors, all similar, example:-

coot_wrap_guile.cc: In function ‘scm_unused_struct* _wrap_vector_mtz_type_label_ref(SCM, SCM)’:
coot_wrap_guile.cc:3691:24: error: ‘scm_listify__GONE__REPLACE_WITH__scm_list_n’ was not declared in this scope
           SCM_UNDEFINED));
                        ^
coot_wrap_guile.cc: In function ‘scm_unused_struct* _wrap_vector_mtz_type_label_setN___(SCM, SCM, SCM)’:
coot_wrap_guile.cc:3732:24: error: ‘scm_listify__GONE__REPLACE_WITH__scm_list_n’ was not declared in this scope
           SCM_UNDEFINED));
                        ^
make[1]: *** [coot_wrap_guile.lo] Error 1
make[1]: Leaving directory `/s/ems/s/coot/build-coot/src'
make: *** [all-recursive] Error 1
make failed.

This error is a little beyond my C++ knowledge, any idea's how I can get past this ? As far as I can see in 24-guile.txt, the guile 2.2.7 install was fine.
Many Thanks for any help.

**Comment by pemsley** [comment]
Sorry I didn't deal with this at the time.
