### ISSUE TITLE
coot_1.0 for windows

### ISSUE THREAD

**Issue by DmitrySemchonok** [pemsley/coot#66]
Dear colleagues, 

Does Coot 1.0 exist for windows, and what is the installation procedure?

Thanks in advance.

Sincerely,
Dmitry

**Comment by bernhardcl** [comment]
Dear Dmitry,

yes, it exists. Please see and download from:

https://github.com/bernhardcl/coot/releases/tag/Release-1.0.01

There is no installer yet but it will come. I will update the version in 
due course as well...

B

> Dear colleagues,
> 
> Does Coot 1.0 exist for windows, and what is the installation procedure?
> 
> Thanks in advance.
> 
> Sincerely,
> Dmitry
> 
> 
>

**Comment by DmitrySemchonok** [comment]
> Dear Dmitry, yes, it exists. Please see and download from: https://github.com/bernhardcl/coot/releases/tag/Release-1.0.01 There is no installer yet but it will come. I will update the version in due course as well... B
> […](#)
> Dear colleagues, Does Coot 1.0 exist for windows, and what is the installation procedure? Thanks in advance. Sincerely, Dmitry

Dear Bernhard @bernhardcl, thanks a lot!

Kind regards,
Dmitry
