### ISSUE TITLE
Unexpected window minimize

### ISSUE THREAD

**Issue by uebmaster** [pemsley/coot#68]
We've installed coot included with ccp4 last version, but when we try to delete a residue/monomer, coot's window minimize in unexpected way.

I attach a video to show it:

https://drive.google.com/file/d/1-K33wHSmydzSU6_fuYl_ZCHAlybSEtrA/view?usp=sharing

OS: Mac OS Ventura 13.0.1

What is happening?

Thanks in advance.

PD: Sorry for my bad English.

**Comment by pemsley** [comment]
I somehow have skipped this until now. Thanks @uebmaster and @angelobanse.

I don't know what is going on here, but I suspect a problem with the conversion of Quartz events to GTK.
