### ISSUE TITLE
Suggestion for proportional editing - filter by connectivity?

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#85]
Hi,

I like the capacity ("proportional editing") of being able to alter the sphere of influence of dragged refinement.

However, often I might want to move a fairly large section (let's say a helix) that is physically close to other regions that are far away in sequence space (which I don't want to move). If I make the radius too small, I will just drag one atom, and disrupt the helix, and if I make it too large, then other elements that are far away in sequence (which I don't want to move) will come along for the ride.

Would it be possible in a future version of Coot to add a proportional editing mode that works in sequence space? so that rather than dropping off with radius in angstroms, the degree of influence in dragged refinement drops off in an expanding radius in the sequence (either side of the dragged residue)?

Cheers
Oli

**Comment by pemsley** [comment]
> I like the capacity ("proportional editing") of being able to alter the sphere of influence of dragged refinement.

Credit where it's due... I saw the idea (or something like it) in Blender and in Tristan's Isolde before I implemented it in Coot.

**Comment by pemsley** [comment]
If I wanted to drag away a helix, I'd make 4.2 A local distance restraints and a tight (0.001) alpha value.

**Comment by olibclarke** [comment]
Fair enough! I would think that 4.2Å restraints would still make restraints between a helix and surrounding regions though? if there are H-bonds or VdW interactions?

**Comment by pemsley** [comment]
Indeed there will be "outside" interactions, but I would home/imagine that they are relatively few and "tearable"
