### ISSUE TITLE
Undo doesn't work

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#90]
1. Load 3CH3 & map from EDS
2. Pepflif random residue
3. Press undo on sidebar
4. Nothing happens, except for this dialog (with nothing in the dropdown):

<img width="204" alt="image" src="https://github.com/pemsley/coot/assets/19766818/e44bf0dd-5654-45e1-bbb0-76b517e562b2">

In the terminal we have this:
```
ERROR:: in fill_combobox_with_undo_options() combobox_molecule is null
Gtk-Message: 11:25:26.883: GtkDialog mapped without a transient parent. This is discouraged.
ERROR:: in fill_combobox_with_undo_options() combobox_molecule is null
Gtk-Message: 11:26:15.747: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by olibclarke** [comment]
Progress in the latest commit (`15deae0`), undo now works, but redo does not (same symptoms as previously reported for undo, but now for redo).

**Comment by pemsley** [comment]
Thanks. Confirmed.
