### ISSUE TITLE
None of the ribbon representations work

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#93]
On Mac, 1.06-pre. Clicking any of the ribbon modes (in "Draw...Molecule...") does nothing. Representative message in terminal:

```
widget main_window_meshes_frame was not found
DEBUG:: in mcit::add_molecular_representation() atom_selection: // colour_scheme: Chain style: Ribbon
Error:: ColorScheme::addRule(): null rule
Error:: ColorScheme::addRule(): null rule
Error:: ColorScheme::addRule(): null rule
Error:: ColorScheme::addRule(): null rule
Error:: ColorScheme::addRule(): null rule
INFO:: get_molecular_triangles_mesh() n_primitives: 71
DEBUG:: mcit::add_molecular_representation() ... for molecule 15 we have 6 meshes
DEBUG:: update_main_window_molecular_representation_widgets() n_mesh 6
```

**Comment by olibclarke** [comment]
Progress in latest commit (`15deae0`):

I can now get one of the ribbon modes to load once, and only once, when I first start up the program. E.g. if I try "Ribbon by chain", that works, and subsequent attempts with "Ribbon Rainbow" fail with the previous error. When it does work, the same error appears though (see below). Also, there doesn't seem to be a way to get rid of the ribbons once shown - clearing generic display objects doesn't do it, and there is no separate entry in display manager.

```
widget main_window_meshes_frame was not found
DEBUG:: in mcit::add_molecular_representation() atom_selection: // colour_scheme: Chain style: Ribbon
Error:: ColorScheme::addRule(): null rule
Error:: ColorScheme::addRule(): null rule
Error:: ColorScheme::addRule(): null rule
Error:: ColorScheme::addRule(): null rule
Error:: ColorScheme::addRule(): null rule
INFO:: get_molecular_triangles_mesh() n_primitives: 71
DEBUG:: mcit::add_molecular_representation() ... for molecule 0 we have 1 meshes
DEBUG:: update_main_window_molecular_representation_widgets() n_mesh 1
```

**Comment by pemsley** [comment]
`coot.set_draw_mesh(imol, mesh_idx, state)`

where `imol` annd `mesh_idx` have zero-based indexing and `state` is 1 for on and 2 for off.

**Comment by pemsley** [comment]
The failure to draw ribbons should be fixed in 7a545e48bf3aaf02eb1570afa838384ab81d0eaf.

The control dialog I will do another day.

**Comment by pemsley** [comment]
The "another day" was today.  Now we have a small simple dialog for ribbon display control.

Fixed in 495b2449eea31ced68ed38392e163df2999c3f99.

**Comment by olibclarke** [comment]
Great! Tried it out, works well. Might be good to have a delete button to remove unneeded ribbon representations.

Ribbons still a bit flaky - sometimes they just won't launch, I haven't isolated what triggered the failure yet. Also, after ribbon representation, and then rigid body refinement of the molecule, the ribbon dialog won't close (clicking the red button does nothing).

**Comment by pemsley** [comment]
Seems OK to me now,
