### ISSUE TITLE
Difference map peaks dialog does not find difference map peaks

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#99]
Hi,

The Difference Map Peaks dialog in the Validation menu in 1.06-pre seems to be broken - it does not find difference map peaks, no matter the threshold set. E.g. try 1BL8, which has a pretty obvious ~6.5sig positive peak in the middle of the channel.

Cheers
Oli

**Comment by pemsley** [comment]
Confirmed - thanks.

**Comment by pemsley** [comment]
Fixed in  72f229236ba791a8cf23b2b9f204d470af3e92e2.

**Comment by olibclarke** [comment]
Hi @pemsley  - I just tested this using the latest commit with 1BL8, and it does not seem to be fixed:
<img width="834" alt="image" src="https://github.com/pemsley/coot/assets/19766818/578da122-d2cb-4fc3-8552-b30af6b26e80">
